### ISSUE TITLE
Ajustar explorador

### ISSUE THREAD

**Issue by carlosfpardo** [datasketch/mobility-actions-app#3]
- En todas las visualizaciones: Si la variable es con base de continuidad, que haya gradación de color y no colores distintos
- En todas: agregar pie de gráfica con la mejor fuente (tal vez la que puse en attribution en credits y con link al about?), hacer lo mismo con las imágenes que se descargan
- En mapa: agregar visualización según ciudades (punto en vez de polígono) para que se puedan ver las variables según color y tamaño de los círculos en cada ciudad
- En las gráficas de cuadraditos (no me acuerdo cómo se llaman): que haya un label (cómo se define cuál es dónde?)
- Cambiar la de los círculos concéntricos por la que hemos usado antes (eje X Y y pepas que se pueden usar de tamaño y color).

**Comment by lenafm** [comment]
1. cerrado
2. cerrado (pero falta el link; lo voy a agregar una vez que lo tengamos)
3. No hay información sobre la latitud y la longitud en los datos, por eso no pude hacer esto.
4. cerrado
5. Esto no hice porque no hay variables numericás (aparte del Budget, y esta sólo no es nula en 17 casos) que se pondría en eje X y Y. Si hay otras variables numericás que que se me escaparon me avisan por favor.

**Comment by carlosfpardo** [comment]
Bien. Sobre 3, entendí que uds podían encontrar X y Y de las ciudades pero aclárenme (tal vez Juan Pablo puede aclarar, no lo pude taguear acá).
Sobre 2, sugiero esta cita textualmente (la que está ahí tiene orden y puntuación distinta):
Sources of data:  "It wasn't so hard" Covid-19 mobility database. PBIC, NUMO, Mobility Works, Streetplans, EpiAndes, Datasketch (2020). Full citation details at bit.ly/mobility-actions

**Comment by lenafm** [comment]
Listo, ya cambio el fuente por el que sugieres.

Sobre 3 - @jpmarindiaz, puede ser que todavía estoy confundida sobre esto, podrías aclarar?

**Comment by jpmarindiaz** [comment]
En este momento la herramienta de cruces no funciona para la variedad y formatos de ciudades de prueba. Todavía no cubrimos todos los países, por eso no lo podemos hacer para esta semana. Pero una vez terminemos la herramienta de geo-coding genérica (en un par de semanas) lo podemos complementar

**Comment by carlosfpardo** [comment]
Ok vale. En mi ignorancia mientras tanto iba buscando si hay un paquete de r que haga eso (un merge que vea nombre de ciudad y el centroide xy de esa ciudad) y vi esto: https://www.jessesadler.com/post/geocoding-with-r/ . Me avisan entonces pero lo que vamos está bien chévere

**Comment by carlosfpardo** [comment]
Creo que ya está todo esto de la lista (lo del link que hablábamos creo que se resuelve en la plataforma con la sección de créditos, y con lo que está en el pie de gráfica ya estamos. Pero creo que para ser más precisos con lo que presenta cada opción sugiero que:
- El nombre "explorative visualization" creo que debería cambiarse simplemente por "Graphs"
- El nombre "actions by country" debería ser más bien "maps by country" (y todos los demás "actions" más bien "maps" y quedaría más fácil de entender).

**Comment by lenafm** [comment]
Acabo de cambiar los nombres de acuerdo a lo que sugiriste.
