### ISSUE TITLE
Descarga de datos completos

### ISSUE THREAD

**Issue by carlosfpardo** [datasketch/mobility-actions-app#5]
Hola,

No estoy seguro si esto va  estar en este repo o en el otro (de la pg) pero es importante tener acceso a un botón que deje descargar o acceder a la base completa. Yo no tengo problema con que pongan un botón que lleve al drive en view only (como está ahora) o quedo atento a sus sugerencias.  @lenafm cómo ves? Ah, y sí es importante poder descargar el CSV de la gráfica que se produzca. ¿Se puede?

**Comment by lenafm** [comment]
Hola Carlos,
Ambas cosas deberían ser posible.
- Para la base de datos completa, tendrías que crear copia con acceso de view only con un link. Si me envias este link yo puedo poner un botón en la app que dice algo como "View complete dataset" y te lleva al Google Sheet. Te parece?
- Para el CSV de la gráfica, puedo poner otro botón que dice "Download CSV of current data selection" que descarga un CSV con los datos que producen la gráfica actual.

**Comment by carlosfpardo** [comment]
Tal cual. El drive es este:
https://docs.google.com/spreadsheets/d/1T8LE4p0-L96xiVtHsqARHiLsHsFwS8oQAT1Y2KteMXc/
